# Generated by Django 4.1 on 2022-09-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarky', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
            options={
                'verbose_name': 'Imaj',
                'verbose_name_plural': 'Atik yo',
            },
        ),
        migrations.DeleteModel(
            name='Imajes',
        ),
    ]
