# Generated by Django 4.1 on 2022-09-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermarky', '0003_alter_imaj_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imaj',
            options={'verbose_name': 'Imaj', 'verbose_name_plural': 'Imaj yo'},
        ),
        migrations.AlterField(
            model_name='imaj',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
